verbose: true
seed: 0
use_gpu_1_only: false

backbone_model: resnet18
encoder_output_dim: 128
predictor_output_dim: 1
pretrained: true #
freeze_encoder: true
trained_encoder_file: ../../outputs/archive/best_encoder_pretrained.pth
discretize_labels: true
num_classes: 10

base_dir: ../../outputs/current
test_name: resnet_18_regression_predictor
initial_model_file_name: initial_model.pth #
best_model_file_name: best_model.pth
dataset_description_file_name: dataset_description.txt

data_folder: ../../data/utkface/UTKFace
augmentations: crop,flip,color,grayscale #
split: default
val_size: 0.15
test_size: 0.15
train_size: 0.7 #

batch_size: 512
num_epochs: 3
learning_rate: 0.5
optimizer: sgd
weight_decay: 1e-6
momentum: 0.9
scheduler: cosine
loss_regularization: 0.5

temperature: 2.0 #

key_metric: train_loss
mode: min
save_best_model: true
use_early_stopping: false
save_intermediate_models: true
write_to_tensorboard: true

training_metrics:
  - embedding_norm
  - embedding_variance
  - grad_norm
  - lr

nearest_neighbors: 5
